-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Logger.Object.User exposing (admin, email, id, insertedAt, logs, password, passwordHash, username, verified)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Logger.InputObject
import Logger.Interface
import Logger.Object
import Logger.Scalar
import Logger.ScalarCodecs
import Logger.Union


admin : SelectionSet Bool Logger.Object.User
admin =
    Object.selectionForField "Bool" "admin" [] Decode.bool


email : SelectionSet String Logger.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


id : SelectionSet Int Logger.Object.User
id =
    Object.selectionForField "Int" "id" [] Decode.int


insertedAt : SelectionSet Logger.ScalarCodecs.NaiveDateTime Logger.Object.User
insertedAt =
    Object.selectionForField "ScalarCodecs.NaiveDateTime" "insertedAt" [] (Logger.ScalarCodecs.codecs |> Logger.Scalar.unwrapCodecs |> .codecNaiveDateTime |> .decoder)


logs : SelectionSet decodesTo Logger.Object.Log -> SelectionSet (List decodesTo) Logger.Object.User
logs object_ =
    Object.selectionForCompositeField "logs" [] object_ (identity >> Decode.list)


password : SelectionSet String Logger.Object.User
password =
    Object.selectionForField "String" "password" [] Decode.string


passwordHash : SelectionSet String Logger.Object.User
passwordHash =
    Object.selectionForField "String" "passwordHash" [] Decode.string


username : SelectionSet String Logger.Object.User
username =
    Object.selectionForField "String" "username" [] Decode.string


verified : SelectionSet Bool Logger.Object.User
verified =
    Object.selectionForField "Bool" "verified" [] Decode.bool
