-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Logger.Object exposing (Event(..), Log(..), User(..))


type Event
    = Event


type Log
    = Log


type User
    = User
