-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Logger.ScalarCodecs exposing (NaiveDateTime, codecs)

import Json.Decode as Decode exposing (Decoder)
import Logger.Scalar exposing (defaultCodecs)


type alias NaiveDateTime =
    Logger.Scalar.NaiveDateTime


codecs : Logger.Scalar.Codecs NaiveDateTime
codecs =
    Logger.Scalar.defineCodecs
        { codecNaiveDateTime = defaultCodecs.codecNaiveDateTime
        }
